### ISSUE TITLE
Document node

### ISSUE THREAD

**Issue by BjarneBepaData** [PinkDot-AI/eschergraph#77]
Add a document node (at level 3) for each document that is added to the graph. This improves scalability and makes the EscherGraph more suitable for many documents.

## Design choices
- The document node is linked to the Document object (both have the same id).
- The document node's name is the filename of the document.
- The document's keywords are extracted by providing the entire text (less noisy than aggregated).
- The document's summary is also extracted by summarizing over the entire text.
- Inter-document relations are not (yet) considered.

## Tasks
- [ ] Add the document node as a step in the building pipeline
- [ ] Extract keywords for each document
- [ ] Obtain a summary for each document
