### ISSUE TITLE
Document filter conditions

### ISSUE THREAD

**Issue by BjarneBepaData** [PinkDot-AI/eschergraph#78]
Add structured data to the Document data object to allow for filtering based on these conditions in the search.

## Tasks
- [x] Find a way to provide the structured (meta)data to the document
- [x] An interface for the user and the LLM to filter based on the structured data
- [x] Strategy for dealing with alternative schemas and filtering (semi-structured)

## Design choices
As this is still an experimental feature and we are not yet sure how this will be used in the future, it is best to keep things as simple as possible when implementing this feature. In other words, we will optimize this once we know more. For now, we add a dictionary of tags to the Document data object. The user can deal with varying schemas (tags provided) by deciding whether a missing tag should be ignored or exclude a document.
