### ISSUE TITLE
Reimplement community building

### ISSUE THREAD

**Issue by BjarneBepaData** [PinkDot-AI/eschergraph#79]
During an evaluation of the graph, we discovered that the current community building approach does not work very well. In fact, the current approach introduces quite a lot of noise and seems to be suboptimal compared to straightforward document topic identification.

## Tasks
- [ ] Identify the main topics in the document and convert them into nodes in level 1
- [ ] Add edges between the main topics by adding the previous call as messages
- [ ] Match level 0 nodes to a main topic in level 1 based on embedding similarity and reranking
- [ ]  Update the visualization to deal with the new "clusters"
